source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }


gem "rails", "~> 7.0.2", ">= 7.0.2.3"
gem 'haml-rails'
gem "pg", "~> 1.1"
gem 'activerecord', require: false
gem 'sequel', '>= 5.43.0', require: false
gem 'sequel-rails', require: false
gem 'sequel_secure_password', require: false
gem "puma", "~> 5.0"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

group :development do
  gem "web-console"
end

group :test do
  gem 'database_cleaner-active_record', require: false
  gem 'database_cleaner-sequel', require: false
end

group :development, :test do
  gem 'appmap', path: '../../..'
  gem 'pry-byebug', '>=0', '< 99'
  gem 'rspec-rails'
end
