AllCops:
  NewCops: enable

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

# We have squiggly heredocs
Layout/HeredocIndentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  ExcludedMethods:
  - it
  - context

Style/MultilineBlockChain:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
