AllCops:
  NewCops: enable

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

# We have squiggly heredocs
Layout/HeredocIndentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/MultilineBlockChain:
  Enabled: false

Style/NumericPredicate:
  Enabled: false
  
Style/AndOr:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
