#!/usr/bin/env ruby

$LOAD_PATH.unshift File.join(__dir__, '..', 'lib')

require 'json'
require 'mock_webapp/user'
require 'mock_webapp/request'
require 'mock_webapp/controller'

include MockWebapp

puts JSON.pretty_generate Controller.instance.process(Request.new(id: 'alice'))
