source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.3'

gem 'pg'
gem 'sequel', '= 5.20.0'
gem 'sequel-rails'
gem 'sequel_secure_password'

appmap_gem_opts = { require: %w[appmap appmap/railtie] }
appmap_gem_opts[:path] = '../../..' if File.exist?('../../../appmap.gemspec')
gem 'appmap', appmap_gem_opts

group :development, :test do
  gem 'rspec-rails'
  # Required for Sequel, since without ActiveRecord, the Rails transactional fixture support
  # isn't activated.
  gem 'database_cleaner'
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
end

group :development do
end
