#!/usr/bin/env bash
set -e

# Just checking for a healthy container isn't enough, apparently. If
# we don't wait here, sometimes the database is inaccessible.
for i in {1..10}; do
  psql -h pg -U postgres postgres -c 'select 1' && break
  printf ' .'
  sleep 1
done
echo
psql -h pg -U postgres postgres -c 'select 1'

export RAILS_ENV=test
./bin/rake db:{create,migrate,setup}

./bin/rails runner 'User.first_or_create(login: "admin")'

