source 'https://rubygems.org'
git_source(:github) { |name| "https://github.com/#{name}.git" }

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.11'
gem 'haml-rails'

# Use postgresql as the database for Active Record
gem 'pg', '~> 0.15'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
# gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
# gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
# gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

appmap_path = \
  # Support debugging inside the container with volume-mounted source
  if File.directory?('/src/appmap-ruby')
    '/src/appmap-ruby'
  elsif File.exist?('../../../appmap.gemspec')
    '../../..'
  end

if appmap_path
  # Set the branch parameter, so that 'bundle config local.appmap' will work
  appmap_branch = Dir.chdir appmap_path do
    `git rev-parse --abbrev-ref HEAD`.strip
  end
end

appmap_options = \
  if appmap_path && appmap_branch
    { git: appmap_path, branch: appmap_branch }
  elsif appmap_path
    { path: appmap_path }
  else
    {}
  end.merge(require: %w[appmap appmap/railtie])

gem 'appmap', appmap_options

group :development, :test do
  gem 'rspec-rails'
  gem 'database_cleaner'
  
  gem 'pry-byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

