source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'rails', '~> 6'

gem 'haml-rails'

gem 'activerecord', require: false
gem 'pg'
gem 'sequel', '>= 5.43.0', require: false
gem 'sequel-rails', require: false
gem 'sequel_secure_password', require: false

appmap_path = \
  # Support debugging inside the container with volume-mounted source
  if File.directory?('/src/appmap-ruby')
    '/src/appmap-ruby'
  elsif File.exist?('../../../appmap.gemspec')
    '../../..'
  end

if appmap_path
  # Set the branch parameter, so that 'bundle config local.appmap' will work
  appmap_branch = Dir.chdir appmap_path do
    `git rev-parse --abbrev-ref HEAD`.strip
  end
end

appmap_options = \
  if appmap_path && appmap_branch
    { git: appmap_path, branch: appmap_branch }
  elsif appmap_path
    { path: appmap_path }
  else
    {}
  end.merge(require: %w[appmap])

group :development, :test do
  gem 'appmap', appmap_options
  gem 'cucumber-rails', require: false
  gem 'rspec-rails'
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'pry-byebug'
end

group :test do
  gem 'database_cleaner-active_record', require: false
  gem 'database_cleaner-sequel', require: false
end

group :development do
end
