source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'rails', '~> 6'

gem 'haml-rails'

gem 'activerecord', require: false
gem 'pg'
gem "puma", "~> 6.4"
gem 'sequel', '>= 5.43.0', require: false
gem 'sequel-rails', require: false
gem 'sequel_secure_password', require: false

group :development, :test do
  gem 'appmap', path: '../../..'
  gem 'cucumber-rails', require: false
  gem 'rspec-rails'
  gem "rswag-specs", "~> 2.8.0" # RSwag - Swagger-based DSL for rspec & accompanying rake task for generating Swagger files
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'pry-byebug'
end

group :test do
  gem 'database_cleaner-active_record', require: false
  gem 'database_cleaner-sequel', require: false
end

group :development do
end
