#!/usr/bin/env ruby

$LOAD_PATH.unshift File.join(File.dirname(__FILE__), '../lib')

require 'appmap'
require 'appmap/inspect'
require 'appmap/config'

def usage
  warn 'Usage: inspect <config-file>'
  exit 1
end

config_file_name = ARGV.shift || '.appmap.yml'
usage unless ARGV.empty?

config = AppMap::Config.load_from_file(config_file_name)
features = config.map(&AppMap::Inspect.method(:detect_features))
features = features.map(&:reparent)
features.each(&:prune)

puts JSON.pretty_generate(features)
