#!/usr/bin/env ruby

require 'json'

$LOAD_PATH.unshift File.join(File.dirname(__FILE__), '../lib')

require 'appmap'
require 'appmap/annotation'
require 'shellwords'

def usage
  warn 'Usage: trace <pid> <inspect-file>'
  exit 1
end

pid = ARGV.shift || usage
inspect_file = ARGV.shift || usage
usage unless ARGV.empty?

inspect_data = JSON.parse(File.read(inspect_file))
annotations = inspect_data.map { |entry| AppMap::Annotation.from_hash(entry) }

method_names = annotations.map(&:collect_methods).flatten.map do |method|
  separator = method.static? ? '.' : '#'
  [ method.class_name, method.name ].join(separator)
end

method_args = method_names.map(&:shellescape)
command = "rbtrace --devmode -p #{pid.to_i} -m #{method_args.join(' ')}"
$stderr.puts command
exec(command)
