source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'rails', '~> 5'

gem 'haml-rails'

gem 'activerecord', require: false
gem 'pg'
gem 'sequel', '= 5.20.0', require: false
gem 'sequel-rails', require: false
gem 'sequel_secure_password', require: false

group :development, :test do
  gem 'appmap', path: '../../..'
  gem 'cucumber-rails', require: false
  gem 'rspec-rails'
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'pry-byebug'
end

group :test do
  # Require only one of these.
  # 'database_cleaner' requries 'database_cleaner-active_record', so don't require it.
  gem 'database_cleaner-active_record', require: false
  gem 'database_cleaner-sequel', require: false
end

group :development do
end
